#!/bin/busybox sh

/bin/busybox --install -s /bin

mkdir -p /dev /proc /sys /etc
mount -t devtmpfs none /dev
mount -t proc    none /proc
mount -t sysfs   none /sys


ip link set eth0 up
# -q: exit immediately after lease;  -n: exit if no lease obtained after 9s
udhcpc -i eth0 -s /udhcpc.sh -q -n

DEVICE= URL=
for arg in $(cat /proc/cmdline); do
  case $arg in
    device=*) DEVICE=${arg#device=} ;;
    url=*)    URL=${arg#url=} ;;
  esac
done

if [ -n "$DEVICE" ]; then
  echo "Target Device: $DEVICE <  $URL"
  wget -O - "$URL" | gunzip > "$DEVICE"
  reboot -f
else
  nc -l -p 23333 -e /bin/sh &
fi

exec /bin/sh